apiVersion: v1
kind: Service
metadata:
  namespace: robot-shop
  name: shipping
  labels:
    service: shipping
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: shipping
