apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace : cassandra
spec:
  type: LoadBalancer
  ports:
  - port: 9042
    protocol: TCP
  selector:
    app: cassandra
---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
