apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace : cassandra
spec:
  ports:
  - port: 9042
  selector:
    app: cassandra
  type: LoadBalancer
---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
